name: Google News RSS Feed

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create simple README with news links
        run: |
          # Create a simple README with direct links
          cat > README.md << EOF
          # News Tracker

          This repository provides direct links to Google News RSS feeds for various topics.
          
          Last updated: $(date -u)
          
          ## Direct RSS Feeds
          
          ### General News
          - [Top Headlines RSS Feed](https://news.google.com/rss)
          
          ### Technology
          - [Technology News RSS Feed](https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGRqTVhZU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en)
          
          ### Business
          - [Business News RSS Feed](https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRFp1ZEdvU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en)
          
          ### Science
          - [Science News RSS Feed](https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRFp0Y1RjU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en)
          
          ### Health
          - [Health News RSS Feed](https://news.google.com/rss/topics/CAAqIQgKIhtDQkFTRGdvSUwyMHZNR3QwTlRFU0FtVnVLQUFQAQ?hl=en-US&gl=US&ceid=US:en)
          
          ### Entertainment
          - [Entertainment News RSS Feed](https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNREpxYW5RU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en)
          
          ### Sports
          - [Sports News RSS Feed](https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRFp1ZGpBU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US:en)
          
          ## How to Use
          
          These links can be added to any RSS reader to stay updated with the latest news. Some popular RSS readers include:
          
          - Feedly
          - Inoreader
          - NewsBlur
          - Feedbin
          
          You can also use browser extensions or desktop applications that support RSS.
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update news links: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
